version: "3"
services:
  mysql:
    container_name: mysql1
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123123
    volumes:
      - /docker/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    privileged: true

  nacos:
    image: nacos/nacos-server
    container_name: nacos1
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - MYSQL_DATABASE_NUM=1
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=mysql
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos_config
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=123123
    volumes:
      - /app/cloud/nacos/logs:/home/nacos/logs
    ports:
      - "8849:8848"
    privileged: true
    depends_on:
      - mysql